### ISSUE TITLE
plea for code review

### ISSUE THREAD

**Issue by jgravois** [kaciebig/kaciebig.github.io#2]
summoning my esteemed colleagues @paulcpederson and @ungoldman.

![this is what happens when you google image search 'summoning'](https://f4.bcbits.com/img/a2258561559_10.jpg)

if either (or both) of you could spare any time in the next couple weeks to take a look at http://kacieandjohn.com and provide constructive criticism and/or heckling it would be **most** appreciated.

**Comment by paulcpederson** [comment]
@jgravois I like it. I think you should add more space above the headers in the FAQ:

| Before | After |
| --- | --- |
| <img width="448" alt="screen shot 2017-07-21 at 2 17 35 pm" src="https://user-images.githubusercontent.com/1031758/28482981-d9f16c74-6e1f-11e7-9f56-f3d1b9ba59cc.png"> | <img width="474" alt="screen shot 2017-07-21 at 2 18 08 pm" src="https://user-images.githubusercontent.com/1031758/28482989-e492c56a-6e1f-11e7-901d-69a438549183.png"> |

Also, maybe choose your favorite photo and play with adding it up top or something. Y'all are real beauts, give the people what they want.

**Comment by jgravois** [comment]
agreed! 04dd99a thank you SO much!

**Comment by jgravois** [comment]
@ungoldman you think its worth the trouble for me to use JS to obscure our contact info?

**Comment by ungoldman** [comment]
Hi @jgravois! I'm currently traveling in Ireland, so will try to give this fine site a more thorough review when I'm back Thursday.

As to your question, I don't obscure my email on my site but I also don't share my phone number. If you've got a minute and feel like fooling around with some obfuscation code it probably wouldn't hurt to make it harder for spiders to grab your info. You could also add a `robots.txt` file and disallow all robots from indexing your site if that's a concern (see http://www.robotstxt.org/robotstxt.html for example).

Two small design quibbles -- (1) for the footer, you might want to put the year on a separate line from the icons as it looks a little out of place with the social media icons, and (2) for the header/hero section, I agree with @paulcpederson that a big image showing off the happy couple would be extra nice.

**Comment by jgravois** [comment]
you are **both** heroes among men.

**Comment by jgravois** [comment]
i wanted to do a full width banner image the whole time. i just gave up on the first iteration because i couldn't get it to remotely work.

based on both your inspiration i took another crack at it and the best idea i could come up with was to use a media query to knock down the `vh` on phones.

```css
header .container-fluid
{   
    /*background-color: goldenrod;*/
    background-image: url('/assets/img/3O6A3926.jpg');
    background-repeat: no-repeat;
    background-size: cover;
    height: 75vh;
    padding-top: 36px;
}

@media (max-width: 600px) {
  header .container-fluid {
    height: 35vh;
  }
}
```
i'm sure this is a pretty goofy way to do it, but i can live with the result visually.
